/**
 * Patient profile.
 *
 * Name is two fields, not one: the database stores first and last separately
 * and derives the display name from them, so a single box here would have to be
 * split apart again on the way in — and "Mary Anne Van Der Berg" cannot be.
 *
 * Phone sits with the account details rather than the demographics because it
 * is a reminder channel, which is why it lives beside the notification
 * preferences that decide whether anything is ever sent to it.
 */
import { useEffect, useState, type FormEvent } from 'react';
import { AlertTriangle } from 'lucide-react';
import {
  GENDER_OPTIONS, fetchMyProfile, updateCachedUser, updateMyProfile,
  type Gender,
} from '../../lib/api';
import {
  Alert, Button, Card, Checkbox, Field, Input, PageHeader, Select, Spinner,
} from '../../components/ui';
import { useToast } from '../../components/Toast';

interface FormState {
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
  date_of_birth: string;
  gender: Gender | '';
  insurance_provider: string;
  address: string;
  notify_email: boolean;
  notify_sms: boolean;
}

const EMPTY: FormState = {
  first_name: '',
  last_name: '',
  email: '',
  phone: '',
  date_of_birth: '',
  gender: '',
  insurance_provider: '',
  address: '',
  notify_email: true,
  notify_sms: false,
};

export default function Profile() {
  const toast = useToast();
  const [form, setForm] = useState<FormState>(EMPTY);
  const [loaded, setLoaded] = useState(false);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    fetchMyProfile()
      .then(({ profile }) => {
        setForm({
          first_name: profile.first_name || '',
          last_name: profile.last_name || '',
          email: profile.email || '',
          phone: profile.phone || '',
          date_of_birth: profile.date_of_birth ? profile.date_of_birth.slice(0, 10) : '',
          gender: profile.gender || '',
          insurance_provider: profile.insurance_provider || '',
          address: profile.address || '',
          notify_email: profile.notify_email,
          notify_sms: profile.notify_sms,
        });
        setLoaded(true);
      })
      .catch((err) => setError((err as Error).message));
  }, []);

  function set<K extends keyof FormState>(key: K, value: FormState[K]) {
    setForm((f) => ({ ...f, [key]: value }));
  }

  async function onSubmit(e: FormEvent) {
    e.preventDefault();
    setError('');
    setBusy(true);
    try {
      const { profile } = await updateMyProfile({
        first_name: form.first_name.trim(),
        last_name: form.last_name.trim(),
        phone: form.phone.trim() || null,
        date_of_birth: form.date_of_birth || null,
        gender: form.gender || null,
        insurance_provider: form.insurance_provider.trim() || null,
        address: form.address.trim() || null,
        notify_email: form.notify_email,
        notify_sms: form.notify_sms,
      });
      // full_name comes back generated by the database — take theirs rather
      // than stitching the two fields together a second time here.
      updateCachedUser({
        first_name: profile.first_name,
        last_name: profile.last_name,
        full_name: profile.full_name,
        phone: profile.phone,
        notify_email: profile.notify_email,
        notify_sms: profile.notify_sms,
      });
      toast('Profile updated.', 'success');
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div className="mx-auto max-w-2xl">
      <PageHeader
        title="My profile"
        subtitle="Keep your contact, insurance and reminder settings up to date."
      />

      {error && (
        <Alert tone="error" icon={AlertTriangle} className="mb-6">
          {error}
        </Alert>
      )}
      {!loaded && !error && <Spinner />}

      {loaded && (
        <form onSubmit={onSubmit}>
          <Card title="Your details" className="mb-6">
            <div className="grid gap-x-4 sm:grid-cols-2">
              <Field label="First name" htmlFor="first_name" required>
                <Input
                  id="first_name"
                  autoComplete="given-name"
                  value={form.first_name}
                  onChange={(e) => set('first_name', e.target.value)}
                  required
                />
              </Field>
              <Field label="Last name" htmlFor="last_name" required>
                <Input
                  id="last_name"
                  autoComplete="family-name"
                  value={form.last_name}
                  onChange={(e) => set('last_name', e.target.value)}
                  required
                />
              </Field>

              <Field
                label="Email"
                htmlFor="email"
                hint="Used to sign in, so it can't be changed here."
                className="sm:col-span-2"
              >
                <Input id="email" value={form.email} disabled />
              </Field>

              <Field label="Phone" htmlFor="phone" hint="Where appointment reminders are sent.">
                <Input
                  type="tel"
                  id="phone"
                  autoComplete="tel"
                  placeholder="e.g. 917-555-0100"
                  value={form.phone}
                  onChange={(e) => set('phone', e.target.value)}
                />
              </Field>
              <Field label="Date of birth" htmlFor="date_of_birth">
                <Input
                  type="date"
                  id="date_of_birth"
                  autoComplete="bday"
                  value={form.date_of_birth}
                  onChange={(e) => set('date_of_birth', e.target.value)}
                />
              </Field>

              <Field label="Gender" htmlFor="gender">
                <Select
                  id="gender"
                  value={form.gender}
                  onChange={(e) => set('gender', e.target.value as Gender | '')}
                >
                  <option value="">Not specified</option>
                  {GENDER_OPTIONS.map((g) => (
                    <option key={g.value} value={g.value}>
                      {g.label}
                    </option>
                  ))}
                </Select>
              </Field>
              <Field label="Insurance provider" htmlFor="insurance_provider">
                <Input
                  id="insurance_provider"
                  placeholder="e.g. BlueCross"
                  value={form.insurance_provider}
                  onChange={(e) => set('insurance_provider', e.target.value)}
                />
              </Field>

              <Field label="Address" htmlFor="address" className="mb-0 sm:col-span-2">
                <Input
                  id="address"
                  autoComplete="street-address"
                  value={form.address}
                  onChange={(e) => set('address', e.target.value)}
                />
              </Field>
            </div>
          </Card>

          <Card title="Notifications" className="mb-6">
            <Checkbox
              label="Email reminders"
              checked={form.notify_email}
              onChange={(e) => set('notify_email', e.target.checked)}
            />
            <Checkbox
              label="Text message (SMS) reminders"
              checked={form.notify_sms}
              onChange={(e) => set('notify_sms', e.target.checked)}
            />
            <p className="mt-2 text-xs text-slate-500">
              Reminders are simulated in this prototype.
            </p>
          </Card>

          <Button type="submit" id="submit" variant="primary" loading={busy}>
            {busy ? 'Saving…' : 'Save changes'}
          </Button>
        </form>
      )}
    </div>
  );
}
